In [2]:
import numpy as np
import pandas as pd

In [3]:
my_list = [10,20,30]
pd.Series(data=my_list,index=['a','b','c'])

a    10
b    20
c    30
dtype: int64

In [6]:
d = {'a': 1, 'b': 2, 'c': 3}
ser = pd.Series(data=d)
ser

a    1
b    2
c    3
dtype: int64

In [33]:
ser1 = pd.Series([1,2,3,4],index = ['USA','Germany','USSR','Japan'])
print(ser1)
type(ser1)

USA        1
Germany    2
USSR       3
Japan      4
dtype: int64


pandas.core.series.Series

In [31]:
ser1[0]
ser1["USSR"]

3

In [14]:
print(ser1[1:3])

Germany    2
USSR       3
dtype: int64


In [15]:
ser1 + 1

USA        2
Germany    3
USSR       4
Japan      5
dtype: int64

In [18]:
#masking
ser1[ser1%2 == 0]

Germany    2
Japan      4
dtype: int64

In [50]:
#dataframe
#dt = np.ones((334,5))
dt = np.ones((5,4))
print(dt)
df = pd.DataFrame(dt ,index=['a','b','c','d','e'] ,columns=['A','B','C','D'])
#df = pd.DataFrame(np.random.rand(334,5),index=np.arange(334))
df

[[1. 1. 1. 1.]
 [1. 1. 1. 1.]
 [1. 1. 1. 1.]
 [1. 1. 1. 1.]
 [1. 1. 1. 1.]]


A    B    C    D
a  1.0  1.0  1.0  1.0
b  1.0  1.0  1.0  1.0
c  1.0  1.0  1.0  1.0
d  1.0  1.0  1.0  1.0
e  1.0  1.0  1.0  1.0

In [40]:
dict1 = {"one":[1,2,3,4,5],"two":[6,7,8,9,10]}

df = pd.DataFrame(dict1)
df

one  two
0    1    6
1    2    7
2    3    8
3    4    9
4    5   10

In [6]:
df = pd.read_csv("salary.csv")

In [43]:
df

ID  Gender   Salary    Country  Company
0   1    Male  15000.0      India   Google
1   2  Female  45000.0      China      NaN
2   3  Female  25000.0      India   Google
3   4     NaN      NaN  Australia   Google
4   5    Male      NaN      India   Google
5   6    Male  54000.0        NaN  Alibaba
6   7     NaN  74000.0      China      NaN
7   8    Male  14000.0  Australia      NaN
8   9  Female  15000.0        NaN      NaN
9  10    Male  33000.0  Australia      NaN

In [8]:
df.head()

ID  Gender   Salary    Country Company
0   1    Male  15000.0      India  Google
1   2  Female  45000.0      China     NaN
2   3  Female  25000.0      India  Google
3   4     NaN      NaN  Australia  Google
4   5    Male      NaN      India  Google

In [9]:
df.tail()

ID  Gender   Salary    Country  Company
5   6    Male  54000.0        NaN  Alibaba
6   7     NaN  74000.0      China      NaN
7   8    Male  14000.0  Australia      NaN
8   9  Female  15000.0        NaN      NaN
9  10    Male  33000.0  Australia      NaN

In [10]:
df.describe()

ID        Salary
count  10.00000      8.000000
mean    5.50000  34375.000000
std     3.02765  21790.807367
min     1.00000  14000.000000
25%     3.25000  15000.000000
50%     5.50000  29000.000000
75%     7.75000  47250.000000
max    10.00000  74000.000000

In [11]:
#harry
dt = np.ones((334,5))
df = pd.DataFrame(np.random.rand(334,5), index=np.arange(334))
df
type(df)
                  
                  

pandas.core.frame.DataFrame

In [12]:
df.describe()

0           1           2           3           4
count  334.000000  334.000000  334.000000  334.000000  334.000000
mean     0.501145    0.481580    0.536022    0.497633    0.499308
std      0.291912    0.294590    0.286433    0.294476    0.278361
min      0.001594    0.004195    0.004363    0.003742    0.002497
25%      0.238695    0.223555    0.294360    0.239228    0.264349
50%      0.508905    0.476279    0.551126    0.498216    0.496455
75%      0.753843    0.742844    0.775891    0.717770    0.741832
max      0.995705    0.997674    0.998815    0.998116    0.997134

In [13]:
df.dtypes

0    float64
1    float64
2    float64
3    float64
4    float64
dtype: object

In [14]:
df.index

Int64Index([  0,   1,   2,   3,   4,   5,   6,   7,   8,   9,
            ...
            324, 325, 326, 327, 328, 329, 330, 331, 332, 333],
           dtype='int64', length=334)

In [15]:
df.columns

RangeIndex(start=0, stop=5, step=1)

In [16]:
df.sort_index(axis=0, ascending=False)

0         1         2         3         4
333  0.723416  0.888044  0.940620  0.854301  0.636740
332  0.589049  0.388679  0.782702  0.050729  0.354981
331  0.008592  0.760103  0.881068  0.211637  0.775830
330  0.298969  0.421546  0.521570  0.468863  0.788044
329  0.941779  0.087611  0.209701  0.616788  0.259952
..        ...       ...       ...       ...       ...
4    0.012705  0.538790  0.525920  0.963622  0.938720
3    0.191470  0.635386  0.832578  0.879903  0.737430
2    0.215672  0.789656  0.764324  0.464675  0.083304
1    0.527254  0.806383  0.869179  0.216677  0.328796
0    0.263145  0.337519  0.171289  0.767506  0.952479

[334 rows x 5 columns]

In [17]:
df.sort_index(axis=1, ascending=False)
#axis = 0[Row]
#axis = 1[Column]

4         3         2         1         0
0    0.952479  0.767506  0.171289  0.337519  0.263145
1    0.328796  0.216677  0.869179  0.806383  0.527254
2    0.083304  0.464675  0.764324  0.789656  0.215672
3    0.737430  0.879903  0.832578  0.635386  0.191470
4    0.938720  0.963622  0.525920  0.538790  0.012705
..        ...       ...       ...       ...       ...
329  0.259952  0.616788  0.209701  0.087611  0.941779
330  0.788044  0.468863  0.521570  0.421546  0.298969
331  0.775830  0.211637  0.881068  0.760103  0.008592
332  0.354981  0.050729  0.782702  0.388679  0.589049
333  0.636740  0.854301  0.940620  0.888044  0.723416

[334 rows x 5 columns]

In [18]:
df.head()

0         1         2         3         4
0  0.263145  0.337519  0.171289  0.767506  0.952479
1  0.527254  0.806383  0.869179  0.216677  0.328796
2  0.215672  0.789656  0.764324  0.464675  0.083304
3  0.191470  0.635386  0.832578  0.879903  0.737430
4  0.012705  0.538790  0.525920  0.963622  0.938720

In [21]:
newdf = df

In [22]:
newdf[0][0] = 9783


In [23]:
df

0         1         2         3         4
0    9783.000000  0.337519  0.171289  0.767506  0.952479
1       0.527254  0.806383  0.869179  0.216677  0.328796
2       0.215672  0.789656  0.764324  0.464675  0.083304
3       0.191470  0.635386  0.832578  0.879903  0.737430
4       0.012705  0.538790  0.525920  0.963622  0.938720
..           ...       ...       ...       ...       ...
329     0.941779  0.087611  0.209701  0.616788  0.259952
330     0.298969  0.421546  0.521570  0.468863  0.788044
331     0.008592  0.760103  0.881068  0.211637  0.775830
332     0.589049  0.388679  0.782702  0.050729  0.354981
333     0.723416  0.888044  0.940620  0.854301  0.636740

[334 rows x 5 columns]

In [24]:
df = pd.DataFrame({"one":[1,2,3,4,5],
 "two":[6,7,8,9,10],
 "three":[11,12,13,12,17]},
 index=['a','b','c','d','e'])

df
                  
        

one  two  three
a    1    6     11
b    2    7     12
c    3    8     13
d    4    9     12
e    5   10     17

In [25]:
df['new'] = df['one'] + df['two']

In [26]:
df

one  two  three  new
a    1    6     11    7
b    2    7     12    9
c    3    8     13   11
d    4    9     12   13
e    5   10     17   15

In [27]:
df['new2'] = np.where(df['three'] > 12,12,df['three'])

In [28]:
df

one  two  three  new  new2
a    1    6     11    7    11
b    2    7     12    9    12
c    3    8     13   11    12
d    4    9     12   13    12
e    5   10     17   15    12

In [29]:
df

one  two  three  new  new2
a    1    6     11    7    11
b    2    7     12    9    12
c    3    8     13   11    12
d    4    9     12   13    12
e    5   10     17   15    12

In [30]:
df.insert(2,"location",[1,2,3,4,5])
df

one  two  location  three  new  new2
a    1    6         1     11    7    11
b    2    7         2     12    9    12
c    3    8         3     13   11    12
d    4    9         4     12   13    12
e    5   10         5     17   15    12

In [31]:
df

one  two  location  three  new  new2
a    1    6         1     11    7    11
b    2    7         2     12    9    12
c    3    8         3     13   11    12
d    4    9         4     12   13    12
e    5   10         5     17   15    12

In [34]:
df.drop(columns=['new', 'new2'], inplace = True)
df

one  two  location  three
a    1    6         1     11
b    2    7         2     12
c    3    8         3     13
d    4    9         4     12
e    5   10         5     17

In [35]:
values = [['Rohan',455],['Elvish',250],['Deepak',495],
 ['Soni',400],['Radhika',350],['Vansh',450]]
df1 = pd.DataFrame(values,columns=["Name","Number"],index=list("abcdef"))
df1

Name  Number
a    Rohan     455
b   Elvish     250
c   Deepak     495
d     Soni     400
e  Radhika     350
f    Vansh     450

In [36]:
df1.loc['a']

Name      Rohan
Number      455
Name: a, dtype: object

In [38]:
df1.loc[['a','e']]

Name  Number
a    Rohan     455
e  Radhika     350

In [40]:
df1.loc['c' :]['Name']

c     Deepak
d       Soni
e    Radhika
f      Vansh
Name: Name, dtype: object

In [47]:
df1.loc["a":"d","Number"]

a    455
b    250
c    495
d    400
Name: Number, dtype: int64

In [48]:
df1.iloc[0]

Name      Rohan
Number      455
Name: a, dtype: object

In [49]:
df1.iloc[0,0]

'Rohan'

In [50]:
df1.iloc[:4]

Name  Number
a   Rohan     455
b  Elvish     250
c  Deepak     495
d    Soni     400

In [51]:
df1.iloc[1:4]

Name  Number
b  Elvish     250
c  Deepak     495
d    Soni     400

In [52]:
df = pd.DataFrame({"Name":["Rahul","Shyam","Lalit","Ajay","Harish","Sonu"],
 "TotalMarks":[82, 80, 63, 22, 65, 40],
 "Grade": ['A', 'E', 'B','E','C','D'],
 "Subjects":["Math","Biology","Math","Maths","Commerce","Arts"]})

In [53]:
df

Name  TotalMarks Grade  Subjects
0   Rahul          82     A      Math
1   Shyam          80     E   Biology
2   Lalit          63     B      Math
3    Ajay          22     E     Maths
4  Harish          65     C  Commerce
5    Sonu          40     D      Arts

In [54]:
df['TotalMarks']

0    82
1    80
2    63
3    22
4    65
5    40
Name: TotalMarks, dtype: int64

In [55]:
df[df['TotalMarks'] > 45]

Name  TotalMarks Grade  Subjects
0   Rahul          82     A      Math
1   Shyam          80     E   Biology
2   Lalit          63     B      Math
4  Harish          65     C  Commerce

In [57]:
df['TotalMarks'] >45

0     True
1     True
2     True
3    False
4     True
5    False
Name: TotalMarks, dtype: bool

In [62]:
 df[ (df['TotalMarks'] > 45) & (df['Subjects'] == "Math")]

Name  TotalMarks Grade Subjects
0  Rahul          82     A     Math
2  Lalit          63     B     Math

In [64]:
df[ (df['TotalMarks'] > 45) | (df['Subjects'] == 'Math')]

Name  TotalMarks Grade  Subjects
0   Rahul          82     A      Math
1   Shyam          80     E   Biology
2   Lalit          63     B      Math
4  Harish          65     C  Commerce