In [3]:
#Python program to display the fibonacci sequence up to n-th term using recursive function.

def fibonacci_recursive(n):
    if n <= 0:
        return []
    elif n == 1:
        return [0]
    elif n == 2:
        return [0, 1]
    else:
        fib_list = fibonacci_recursive(n-1)
        fib_list.append(fib_list[-1] + fib_list[-2])
        return fib_list

# Input the number of terms
n = int(input("Enter the number of terms for Fibonacci sequence: "))

 #Call the recursive function and display the result
fib_sequence = fibonacci_recursive(n)
print(f"The Fibonacci sequence up to the {n}-th term is:")
print(fib_sequence)


Enter the number of terms for Fibonacci sequence:  20


The Fibonacci sequence up to the 20-th term is:
[0, 1, 1, 2, 3, 5, 8, 13, 21, 34, 55, 89, 144, 233, 377, 610, 987, 1597, 2584, 4181]


In [17]:
#Write a recursive function that compute the sum of number from 1 to n; get the value of last numbers(n) from user.

def recursive_sum(n):
    if n == 1:
        return 1
    else:
        return n + recursive_sum(n - 1)

# Get the value of 'n' from the user
#n = int(input("Enter the value of 'n': "))

# Call the recursive function and display the result
#result = recursive_sum(n)
#print(f"The sum of numbers from 1 to {n} is:", result)

#def recursive_sum(n):
#    if n == 1:
 #       return 1
  #  else:
   #     return n+recursive_sum(n-1)
        



In [5]:
# Make a login portal which allows maximum 3 wrong attempts.
#Use pre-defined username and password to match inputs.
#usr = 'admin' and password='12345'

def login_portal(count=0):
    while count < 2:
        user_id = input("Enter user name")
        password = input("Enter password")
        if user_id=="iota" and password=="indore":
            return "successfull login"
        else:
            print("wrong credentials")
            count=count+1
            return login_portal(count)
        

In [6]:
login_portal()



Enter user name iota
Enter password indore


'successfull login'

In [7]:
#Write a recursive code to find the multiplication of all elements of a list

def recursive_multiply(lst):
    if len(lst) == 0:
        return 1
    else:
        return lst[0] * recursive_multiply(lst[1:])

# Example usage
my_list = [1, 2, 3, 4, 5]

result = recursive_multiply(my_list)
print(f"The multiplication of all elements in the list is: {result}")


The multiplication of all elements in the list is: 120


In [11]:
#Write a function that takes a number and tests if it is prime number using recursion.

def is_prime(n, i=2):
    if n <= 2:
        return n == 2
    if n % i == 0:
        return False
    if i * i > n:
        return True
    return is_prime(n, i + 1)

# Example usage:
num = int(input("Enter a number: "))
result = is_prime(num)
if result:
    print(f"{num} is a prime number.")
else:
    print(f"{num} is not a prime number.")


Enter a number:  23


23 is a prime number.


In [18]:
def recursive_sum(n):
    if n == 1:
        return 1
    else:
        return n + recursive_sum(n - 1)

In [22]:
recursive_sum(20)


210

In [25]:
import numpy as np

In [26]:
lst = [1,2,3,4]
a = np.array([1,2,3,4])
print(lst)
print(a)
print(type(a))

[1, 2, 3, 4]
[1 2 3 4]
<class 'numpy.ndarray'>


In [27]:
a = np.array([[1,2,3],[4,5,6]])

print(a)

print("dimension of a:",a.ndim)

print("shape of a:",a.shape)

print("size of a:",a.size)

[[1 2 3]
 [4 5 6]]
dimension of a: 2
shape of a: (2, 3)
size of a: 6


In [29]:
x = np.array([[1,2,3],[4,5,6]])
x

array([[1, 2, 3],
       [4, 5, 6]])

In [34]:
x[0,1:]

array([2, 3])

In [38]:
b = np.array([1,2,3,4])
b

array([1, 2, 3, 4])

In [40]:
arr = np.arange(10)
print(arr)

filtered = np.where(((arr % 2 == 0) & (arr > 5)),arr,0)
print(filtered)

filtered = np.where(((arr % 2 == 0) & (arr > 5)),arr,0)
print(filtered)


[0 1 2 3 4 5 6 7 8 9]
[0 0 0 0 0 0 6 0 8 0]
[0 0 0 0 0 0 6 0 8 0]
